### ISSUE TITLE
Проверка дз 1

### ISSUE THREAD

**Issue by Alexnovi2004** [nicotinecotine/flutter_todo#1]
Чистота кода и общая структура проекта (max 4 балла) - 3,5
 • Есть up-to-date README со ссылкой на загрузку .apk, перечнем реализованных фич, пара скриншотов (+1 балл)
0,5
 • Форматирование кода присутствует (+1 балл)
1
 • Код разбит на фичи и слои (не важно, feature-first / layer-first) (+2 балла)
2

Вёрстка + навигация (max 16 баллов) - 6,5 
 • Полностью свёрстаны 2 экрана по макетам: основной и добавления/редактирования задачи (+10 баллов). Анимации не ожидаем.
5 - есть ошибки в дизайне и логике 
Провайдеры следует поменять
Основной экран - кнопка не той формы
Дела с важностью и временем выполнения некорректно выглядят, чекбокс без логики 
При свайпе верхнего элемента не пропадает скругленность 

Экран добавления:
Кнопка удалить не должна быть доступна при добавлении задачи

Если редактировать задачу, то она не редактируется, а добавляется новая, причем потом будут траблы с удалением. Удалить конкретную задачу тоже нельзя.
При редактировании вместо того, чтобы показывался текст заметки, чтобы его менять показывается подсказка в виде этого текста(надо не hint text, а initial value) 

 • Свайп по айтему Выполнено/Удалить с логикой (+3 балла)
1,5, тк логика хромает (удаляет больше элементов, чем есть) 
Выполненность не сразу показывается в счетчике 

Было бы лучше свайпом при выполненности отменять выполненность. 

 • Показ выполненных дел с логикой (+3 балла)
0, вообще рандом показывает 
Счетчик дел не обновляется в режиме реального времени. Чтобы отобразилось - нужно нажать кнопку глазика (например). Надо бы изменять состояние при свайпе/чек боксе.
Удаленные дела отмечаются как выполненные иногда 

Разное (max 6 баллов) - 4
 • Реализовано нормальное логирование (не print'ы) (+2 балла)
0, не нашел 
 • Есть человеческая иконка у приложения (iOS или Android) (+4 балла)
4 балла

**Comment by nicotinecotine** [comment]
Привет! 
Спасибо за рецензию! Обо всех проблемах знал, в принципе. Не думал, правда, что очень точное соответствие макету так важно. Не большая же проблема сделать круглую кнопку вместо дефолтной из Material 3, просто решил, что так веселее.

**Comment by nicotinecotine** [comment]
Ну, ладно, не столь важно. Ещё раз спасибо!
